// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChartDonut: typeof import('./src/components/ChartDonut.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    CircleChart: typeof import('./src/components/CircleChart.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    FilterDate: typeof import('./src/components/FilterDate.vue')['default']
    FilterMenu: typeof import('./src/components/FilterMenu.vue')['default']
    GraphBar: typeof import('./src/components/GraphBar.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IAdd: typeof import('./src/components/icons/IAdd.vue')['default']
    IBase: typeof import('./src/components/icons/IBase.vue')['default']
    ICalender: typeof import('./src/components/icons/ICalender.vue')['default']
    ICaretDown: typeof import('./src/components/icons/ICaretDown.vue')['default']
    ICustomers: typeof import('./src/components/icons/ICustomers.vue')['default']
    IDashboard: typeof import('./src/components/icons/IDashboard.vue')['default']
    IFilter: typeof import('./src/components/icons/IFilter.vue')['default']
    IInventory: typeof import('./src/components/icons/IInventory.vue')['default']
    ILogout: typeof import('./src/components/icons/ILogout.vue')['default']
    IMessage: typeof import('./src/components/icons/IMessage.vue')['default']
    Isearch: typeof import('./src/components/icons/Isearch.vue')['default']
    ISetting: typeof import('./src/components/icons/ISetting.vue')['default']
    IShoppingBag: typeof import('./src/components/icons/IShoppingBag.vue')['default']
    ISort: typeof import('./src/components/icons/ISort.vue')['default']
    IStore: typeof import('./src/components/icons/IStore.vue')['default']
    Orders: typeof import('./src/components/orders.vue')['default']
    RecentOrders: typeof import('./src/components/RecentOrders.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SummaryCard: typeof import('./src/components/SummaryCard.vue')['default']
  }
}
