// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseTable: typeof import('./src/components/BaseTable.vue')['default']
    BulkAction: typeof import('./src/components/BulkAction.vue')['default']
    ChartBar: typeof import('./src/components/ChartBar.vue')['default']
    ChartDonut: typeof import('./src/components/ChartDonut.vue')['default']
    ChartLine: typeof import('./src/components/ChartLine.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    ComboBox: typeof import('./src/components/ComboBox.vue')['default']
    CreateCustomerModal: typeof import('./src/components/CreateCustomerModal.vue')['default']
    CustomersTable: typeof import('./src/components/CustomersTable.vue')['default']
    FilterDate: typeof import('./src/components/FilterDate.vue')['default']
    FilterMenu: typeof import('./src/components/FilterMenu.vue')['default']
    IAdd: typeof import('./src/components/icons/IAdd.vue')['default']
    ICalender: typeof import('./src/components/icons/ICalender.vue')['default']
    ICaretDown: typeof import('./src/components/icons/ICaretDown.vue')['default']
    IChart: typeof import('./src/components/icons/IChart.vue')['default']
    ICheck: typeof import('./src/components/icons/ICheck.vue')['default']
    IChevronUpDown: typeof import('./src/components/icons/IChevronUpDown.vue')['default']
    ICustomers: typeof import('./src/components/icons/ICustomers.vue')['default']
    IDashboard: typeof import('./src/components/icons/IDashboard.vue')['default']
    IFilter: typeof import('./src/components/icons/IFilter.vue')['default']
    IImg: typeof import('./src/components/icons/IImg.vue')['default']
    IInventory: typeof import('./src/components/icons/IInventory.vue')['default']
    ILogout: typeof import('./src/components/icons/ILogout.vue')['default']
    IMessage: typeof import('./src/components/icons/IMessage.vue')['default']
    Isearch: typeof import('./src/components/icons/Isearch.vue')['default']
    ISetting: typeof import('./src/components/icons/ISetting.vue')['default']
    IShoppingBag: typeof import('./src/components/icons/IShoppingBag.vue')['default']
    ISort: typeof import('./src/components/icons/ISort.vue')['default']
    IUpload: typeof import('./src/components/icons/IUpload.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NP: typeof import('naive-ui')['NP']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    OrderDialog: typeof import('./src/components/OrderDialog.vue')['default']
    OrdersTable: typeof import('./src/components/OrdersTable.vue')['default']
    ProductsTable: typeof import('./src/components/ProductsTable.vue')['default']
    RecentOrders: typeof import('./src/components/RecentOrders.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SummaryCard: typeof import('./src/components/SummaryCard.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
  }
}
